default: &DEFAULT

  # model
  model: 'resnet'

  # augmentations
  crop_size: 64
  jc_jit_limit: 7

  #  optimizer parameters
  lr: !!float 0.004
  momentum: !!float 0.9
  lr_warmup_epochs: 0
  weight_decay: 0.
  lr_milestones: [60, 90]

  train_data_path: '/tmp/sdss_w_specz_train.h5'
  valid_data_path: '/tmp/sdss_w_specz_valid.h5'
  num_data_workers: 6
  num_channels: 5

  # spec-z
  specz_upper_lim: !!float 0.4
  num_classes: 180

  max_epochs: 100
  batch_size: 256
  valid_batch_size_per_gpu: 512

  log_to_screen: !!bool True
  log_to_tensorboard: !!bool True
  save_checkpoint: !!bool True

  # vit model params
  patch_size: 4
  depth: 6
  embed_dim: 512
  mlp_dim: 512
  num_heads: 8

baseline:
  <<: *DEFAULT

finetuned:
  <<: *DEFAULT

vit:
  <<: *DEFAULT
  model: 'vit'

vit-small: &VITSMALL
  <<: *DEFAULT
  model: 'vit'
  patch_size: 4
  depth: 12
  embed_dim: 384
  num_heads: 6
  mlp_dim: 1536

vit-small-lr1e-2: 
  <<: *VITSMALL
  lr: !!float 0.01


vit-lr-schedule-default:
  <<: *DEFAULT
  model: 'vit'

vit-lr1e-2:
  <<: *DEFAULT
  lr: !!float 0.01
  model: 'vit'

vit-lr5e-2:
  <<: *DEFAULT
  lr: !!float 0.05
  model: 'vit'

vit-lr-schedule:
  <<: *DEFAULT
  lr: !!float 0.001
  weight_decay: 0.
  model: 'vit'

test:
  <<: *VITSMALL
  batch_size: 16
  train_data_path: '/global/cscratch1/sd/shas1693/data/sdss/sdss_w_specz_train.h5'
  valid_data_path: '/global/cscratch1/sd/shas1693/data/sdss/sdss_w_specz_valid.h5'
